config/routes.rb
Dnevnik::Application.routes.draw do

  resources :subjects do as_routes end

  devise_for :users,  :controllers => { :registrations => "users/registrations" }

  resources :users do as_routes end
  resources :roles do as_routes end
  resources :cities do as_routes end
  resources :countries do as_routes end
  resources :jobs do as_routes end
  resources :schools do as_routes end

  get "welcome/index"
  root :to => "welcome#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user
    if user.role? :super_admin
      can :manage, :all
    elsif user.role? :operator
      can [:update, :read], School, ['schools.id in (select su.school_id
                                        from schools_users su
                                        where su.user_id = ?)', user.id] do |school|
        school.editors.include?(user)
      end
    end
  end
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country
  has_many :users
  has_many :schools
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :cities
  has_many :jobs
  has_many :subjects
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :country
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users

end

app/models/school.rb
class School < ActiveRecord::Base
  belongs_to :city
  has_and_belongs_to_many :editors, :class_name => "User"
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :country
end

app/models/user.rb
class User < ActiveRecord::Base

  has_and_belongs_to_many :roles
  has_and_belongs_to_many :schools
  belongs_to :city

  validates_presence_of     :email,                       :if => :email_required?
  validates_format_of       :email, :with  => /^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i , :if => :email_required?
  validates_uniqueness_of   :email,                      :if => :email_required?

  validates_length_of       :password,    :within => 6..20, :on => :create
  validates_format_of       :mobile, :with => /7\d{10}/,  :if => :mobile_required?
  validates_uniqueness_of   :mobile,                      :if => :mobile_required?



  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable    :registerable,  , :validatable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :mobile, :email, :password, :password_confirmation, :remember_me

  def self.find_for_database_authentication(conditions)
     value = conditions[authentication_keys.first]
     where(["mobile = :value OR email = :value", { :value => value }]).first
  end

  # поле для таблиц представление ссылки
  def to_label
    "#{email}"
  end

  def role?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end

  protected

  def email_required?
    self.mobile.blank?
  end

  def mobile_required?
    self.email.blank?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

#  rescue_from CanCan::AccessDenied do |exception|
#    flash[:error] = exception.message
#    redirect_to root_url
#  end

  ActiveScaffold.set_defaults do |config|
    config.ignore_columns.add [:created_at, :updated_at, :password_salt, :encrypted_password,
                                :unlock_token, :last_sign_in_at, :last_sign_in_ip]
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_filter :accessible_roles
  load_and_authorize_resource

  active_scaffold :city do |conf|
    conf.columns[:users].form_ui = :select
    conf.columns[:country].form_ui = :select
  end

  # Get roles accessible by the current user
  #----------------------------------------------------
  def accessible_roles
    @accessible_roles = Role.accessible_by(current_ability)
  end

end 

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_filter :accessible_roles
  load_and_authorize_resource

  active_scaffold :country do |conf|
  end
  # Get roles accessible by the current user
  #----------------------------------------------------
  def accessible_roles
    @accessible_roles = Role.accessible_by(current_ability)
  end

end 

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :accessible_roles
  load_and_authorize_resource

  active_scaffold :job do |conf|
  end

  # Get roles accessible by the current user
  #----------------------------------------------------
  def accessible_roles
    @accessible_roles = Role.accessible_by(current_ability)
  end

end 

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :accessible_roles
  load_and_authorize_resource

  active_scaffold :role do |conf|
  end

  # Get roles accessible by the current user
  #----------------------------------------------------
  def accessible_roles
    @accessible_roles = Role.accessible_by(current_ability)
  end

end 

app/controllers/schools_controller.rb
require "russian_text"
class SchoolsController < ApplicationController
 # before_filter :accessible_roles
  load_and_authorize_resource

  include RussianText

  active_scaffold :school do |conf|
    conf.columns.exclude :editors
    conf.list.columns =  [:title, :address, :city, :editors]
  end

  # Get roles accessible by the current user
  #----------------------------------------------------
  def accessible_roles
    @accessible_roles = Role.accessible_by(current_ability)
  end

  #установим админа создателем этой записи
  def before_create_save(record)
    record.editors << current_user
    record.title = super_capitalize(record.title)
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  active_scaffold :subject do |conf|
  end
end 

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :check_permissions, :only => [:new, :create, :cancel]
  skip_before_filter :require_no_authentication

  def check_permissions
    authorize! :create, resource
  end
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController
  before_filter :get_user, :only => [:index,:new,:edit]
  before_filter :accessible_roles, :only => [:new, :edit, :show, :update, :create]
  load_and_authorize_resource :only => [:show,:new,:destroy,:edit,:update]

  active_scaffold :user do |conf|
    conf.columns = [:email, :mobile, :password, :roles, :city]
    conf.list.columns = [:id, :email, :mobile, :roles]
    conf.columns[:mobile].description = "Телефон в формате 79044418833"
  end

  # Get roles accessible by the current user
  #----------------------------------------------------
  def accessible_roles
    @accessible_roles = Role.accessible_by(current_ability,:read)
  end

  # Make the current user object available to views
  #----------------------------------------
  def get_user
    @current_user = current_user
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #, :except => [:index]
  before_filter :authenticate_user!
  def index
    #@things = current_user.things
    @current_user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = t('application_name')

    -#= stylesheet_link_tag 'jquery-ui-1.8.6.custom', :media => 'screen, projection'
    -#= javascript_include_tag :defaults
    = stylesheet_link_tag 'jquery-ui-1.8.6.custom' , :media => 'screen, projection'
    -#= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.js'
    = javascript_include_tag 'jquery'
    -#= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.4/jquery-ui.js'
    = javascript_include_tag 'jquery-ui-1.8.6.custom.min'
    = javascript_include_tag 'rails' , 'application'

    = stylesheet_link_tag 'grid.css', :media => 'screen, projection'
    = stylesheet_link_tag 'text.css', :media => 'screen, projection'
    = active_scaffold_includes
    = csrf_meta_tag
  %body
    #bodycontainer
      #header
        #logo
          %h1
            = link_to t('application_name'), root_path
        #current_user
          - if user_signed_in?
            %p
              #{t "logged_as"} #{current_user.to_label} #{link_to(t('sign_out'), destroy_user_session_path)}
              %br/
              - if can?(:manage, :user)
                &nbsp;&nbsp;||&nbsp;&nbsp;
                = link_to( t("users"), users_path)
              - if can?(:manage, :city)
                &nbsp;&nbsp;||&nbsp;&nbsp;
                = link_to( t("cities"), cities_path)
              - if can?(:manage, :country)
                &nbsp;&nbsp;||&nbsp;&nbsp;
                = link_to( t("countries"), countries_path)
              - if can?(:manage, :job)
                &nbsp;&nbsp;||&nbsp;&nbsp;
                = link_to( t("jobs"), jobs_path)
              - if current_user.role? :operator
                &nbsp;&nbsp;||&nbsp;&nbsp;
                = link_to( t("schools"), schools_path)

      #container
        #main-content
          - if user_signed_in?
            .flash
              - flash.each do |type, message|
                %div{:class => "message #{type}"}
                  %p= message
            = yield
            - else
              #sidebar
                = yield :sidebar
              #workspace
                = yield

      #footer
        %p
          Copyright &copy; #{Time.now.year} Дневник СМС.

app/views/welcome/index.html.haml
- content_for :sidebar do
  -#= render 'welcome/blabla'
  -# :layout => false)
  -# = render('devise/sessions/new', :locals => {:resources => :users})
  %p
    asdasdasdasdasdasdasdasda

%h1 Welcome#index
%p
  Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
  The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.